package com.nju.scrum.pojo;

public class Attraction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Attraction.aId
     *
     * @mbg.generated
     */
    private Integer aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Attraction.aName
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Attraction.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Attraction.pictureUrl
     *
     * @mbg.generated
     */
    private String pictureurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Attraction.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Attraction.aId
     *
     * @return the value of Attraction.aId
     *
     * @mbg.generated
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Attraction.aId
     *
     * @param aid the value for Attraction.aId
     *
     * @mbg.generated
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Attraction.aName
     *
     * @return the value of Attraction.aName
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Attraction.aName
     *
     * @param aname the value for Attraction.aName
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Attraction.location
     *
     * @return the value of Attraction.location
     *
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Attraction.location
     *
     * @param location the value for Attraction.location
     *
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Attraction.pictureUrl
     *
     * @return the value of Attraction.pictureUrl
     *
     * @mbg.generated
     */
    public String getPictureurl() {
        return pictureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Attraction.pictureUrl
     *
     * @param pictureurl the value for Attraction.pictureUrl
     *
     * @mbg.generated
     */
    public void setPictureurl(String pictureurl) {
        this.pictureurl = pictureurl == null ? null : pictureurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Attraction.description
     *
     * @return the value of Attraction.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Attraction.description
     *
     * @param description the value for Attraction.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    public String toSimpleString() {
        return "Attraction{" +
                "aid=" + aid +
                ", aname='" + aname + '\'' +
                ", pictureurl='" + pictureurl + '\'' +
                '}';
    }
}