package com.nju.scrum.mapper;

import com.nju.scrum.pojo.Apply;
import com.nju.scrum.pojo.ApplyExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface ApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer applyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    @Insert("insert into apply (openid, pid, mess) values " +
            "(#{openid,jdbcType=VARCHAR}, #{pid,jdbcType=INTEGER}, #{mess,jdbcType=VARCHAR})")
    int insert(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    int insertSelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    List<Apply> selectByExample(ApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    Apply selectByPrimaryKey(Integer applyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Apply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Apply record);
}