package com.nju.scrum.mapper;

import com.nju.scrum.pojo.Attraction;
import com.nju.scrum.pojo.attractionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;
@Mapper
public interface AttractionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */

    int deleteByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    int insert(Attraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    int insertSelective(Attraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    List<Attraction> selectByExample(attractionExample example);
    @Select("select * from attraction")
    List<Attraction> selectAll();
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    @Select("select * from attraction where aId = #{aid}")
    Attraction selectByPrimaryKey(Integer aid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attraction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Attraction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attraction record);
}
