package com.nju.scrum.mapper;


import com.nju.scrum.pojo.Plan;
import com.nju.scrum.pojo.planExample;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;
@Mapper
public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    @Insert("insert into plan (creatorName, aName, travelTime, detail) " +
            "values ( #{creatorname,jdbcType=VARCHAR}, #{aname,jdbcType=VARCHAR}, " +
            "#{traveltime,jdbcType=DATE}, #{detail,jdbcType=VARCHAR})")
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    int insertSelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    List<Plan> selectByExample(planExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    Plan selectByPrimaryKey(Integer pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Plan
     *
     * @mbg.generated
     */
    @Update("update plan set applyList = #{applylist,jdbcType=VARCHAR} where pId = #{pid,jdbcType=INTEGER}")
    int updateByPrimaryKey(Plan record);
    @Select("SELECT * FROM PLAN WHERE aName=#{aName}")
    List<Plan> selectByAttraction(String aName);
    @Select("SELECT * FROM PLAN WHERE creatorName=#{uName}")
    List<Plan> selectByCreator(String uName);
}