package com.nju.scrum.pojo;

import java.util.Date;
//备注：Plan类的aid creatorid改为了aname creatorname
public class Plan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.pId
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.creatorId
     *
     * @mbg.generated
     */
    private String creatorname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.aId
     *
     * @mbg.generated
     */
    private String aname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.travelTime
     *
     * @mbg.generated
     */
    private Date traveltime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.detail
     *
     * @mbg.generated
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Plan.applyList
     *
     * @mbg.generated
     */
    private String applylist;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.pId
     *
     * @return the value of Plan.pId
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.pId
     *
     * @param pid the value for Plan.pId
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.creatorName
     *
     * @return the value of Plan.creatorName
     *
     * @mbg.generated
     */
    public String getCreatorname() {
        return creatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.creatorId
     *
     * @param creatorname the value for Plan.creatorId
     *
     * @mbg.generated
     */
    public void setCreatorname(String creatorname) {
        this.creatorname = creatorname == null ? null : creatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.aId
     *
     * @return the value of Plan.aId
     *
     * @mbg.generated
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.aName
     *
     * @param aname the value for Plan.aName
     *
     * @mbg.generated
     */
    public void setAname(String aname) {
        this.aname = aname == null ? null : aname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.travelTime
     *
     * @return the value of Plan.travelTime
     *
     * @mbg.generated
     */
    public Date getTraveltime() {
        return traveltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.travelTime
     *
     * @param traveltime the value for Plan.travelTime
     *
     * @mbg.generated
     */
    public void setTraveltime(Date traveltime) {
        this.traveltime = traveltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.detail
     *
     * @return the value of Plan.detail
     *
     * @mbg.generated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.detail
     *
     * @param detail the value for Plan.detail
     *
     * @mbg.generated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Plan.applyList
     *
     * @return the value of Plan.applyList
     *
     * @mbg.generated
     */
    public String getApplylist() {
        return applylist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Plan.applyList
     *
     * @param applylist the value for Plan.applyList
     *
     * @mbg.generated
     */
    public void setApplylist(String applylist) {
        this.applylist = applylist == null ? null : applylist.trim();
    }
}